### ISSUE TITLE
Enquete para escolher o micro FW (ficará disponivel até dia 30)

### ISSUE THREAD

**Issue by paulodealmeida** [phpba/aquela-arvore-ali-api#10]
Colocar +1 no fw de sua escolha ou sugira um outro não listado.

**Comment by paulodealmeida** [comment]
Lumen

**Comment by paulodealmeida** [comment]
Slim

**Comment by vinaocruz** [comment]
Eu pensei em uma breve discussão sobre o que pesar na escolha. Se for por gosto pessoal ou experiência, pra mim tanto faz. Como havia uma opção entre silex e slim, optei pelo slim por ser mais enxuta.

**Comment by hugohenrique** [comment]
Silex

**Comment by hugohenrique** [comment]
zend-expressive

**Comment by tarsislima** [comment]
Slim ou sílex

**Comment by felipebastosweb** [comment]
Vinao, acho que dá pra levantar algumas vantagens e desvantagens aqui em baixo.

Lumen
 - Bem estruturado por padrao (skeleton)
 - Bom migration (relacional)
 - Bom drive de Database/Orm (relacional)
 - Falta de documentaçao em relaçao ao uso dos recursos do Laravel
 - Ótimo foco no negócio (arquitetura pré-definida)

Slim
 - Pouco estruturado (skeleton simplista)
 - Adapters básicos (não recomenda provider para database, etc)
 - Sem modularizaçao padrão
 - Foco inicial em site básico (necessário definir arquitetura)
 - Toda documentação de adapters (providers) depende dos respectivos autores

Silex
 - Tem algumas opçoes de Skeleton nao padrão (muito flexível)
 - Bom suporte a Adapters (próprio e Doctrine) podendo às vezes serem complexos
 - Alguns adapters (providers) com problema (ex. ODM Mongo)
 - Pouco foco no negócio (foco na arquitetura)
 - Possibilidade de modularização semelhante ao Symfony

**Comment by wgbn** [comment]
Nenhum FM

Sugiro aqui user FIREBASE

"o firebase é um otimo ecossitema para você dar start em vários projetos/negócios, porque não lhe demanda nada além da logica do seu app.

Você não vai precisar de um DB, vai usar o Realtime Database, que é, como o nome diz, reativo e em tempo real. Para você implementar um banco assim na mão, teria de trabalhar com varias coisas, websockets, push,... e por ai vai.

Como escolheram o Angular, você pode também usar o Firebase Hosting para hospedar o app (a versão web) ou pode usar o GitHub Pages, tanto faz. Mas o Hosting do firebase ja vem com SSL, não lembro agora se o GH Pages tem, mas com o SSL você já pode implementar PWA, pois o SSL é uma exigência para isso, e dái sua aplicação fica mauito mais inteligente e offline.

Se precisar de Storage, o Firebase também fornece o serviço.

Push Notifications também.

Tudo isso, serverless. Não precisa programar o servidor, é tudo manejado por apis ou SDKs.

É gratuito para até 100 conexões simultâneas, se passar disso você opta por um plano de $24 mensais.

Pense que 100 conexões simultâneas siginificam 100 usuários fazendo uma requisição no mesmo microssegundo. No dia que o projeto alcançar esse nível de acesso, a base de usuário será imensa e, faça as contas, o projeto já estará se pagando."

**Comment by paulodealmeida** [comment]
vamos de slim
