### ISSUE TITLE
Qual mapa utilizaremos

### ISSUE THREAD

**Issue by edyonil** [phpba/aquela-arvore-ali-api#6]
Hoje já temos diversas opções de mapa livre para usarmos. Qual iremos trabalhar?

- Open Street Map: https://www.openstreetmap.org/#map=5/51.500/-0.100
- Google Maps: https://www.google.com.br/maps

**Comment by gwmoura** [comment]
Eu prefiro Google Maps, mas vou olhar esse openstreetmap

**Comment by paulodealmeida** [comment]
acho o google maps mais tranquilo, tem mais documentação e a atualização está mais fácil de fazer, sem falar da api que o uso é super simples.

**Comment by gwmoura** [comment]
Eu prefiro também, olhei o Open Street Map não gostei muito

**Comment by paulodealmeida** [comment]
e agora que eu vi que já estava previsto em #1 , vou fechar
